"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Recangle_1 = require("./Recangle");
var myshape = new Shape_1.Shape(2, 3);
console.log(myshape.getInfo());
var mycircle = new Circle_1.Circle(2, 3, 1);
console.log(mycircle.getInfo());
var myRec = new Recangle_1.Recangle(0, 0, 3, 1);
console.log(myRec.getInfo());
